# Generated by Django 5.0.2 on 2024-03-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standalonetraffic',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
