# Generated by Django 5.0.2 on 2024-03-11 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_standalonetraffic_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standalonetraffic',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
